shared:
  image: node:8
jobs:
  use_property_file:
    requires: [ ~pr, ~commit ]
    steps:
      - echo: echo test
  use_sonar_opts_env:
    requires: [ ~pr, ~commit ]
    steps:
      - echo: echo test
    environment:
      SD_SONAR_OPTS: '-Dsonar.sources=lib -Dsonar.javascript.lcov.reportPaths=artifacts/coverage/opts/lcov.info'
